### ISSUE TITLE
Link to documentation broken

### ISSUE THREAD

**Issue by FlorianLudwig** [pyupio/dparse#26]
### Description

Link in README.rst to documentation broken (https://dparse.readthedocs.io/)

**Comment by djbrown** [comment]
The link was introduced in the initial commit and hasn't been modified since, neither have the `docs/` contents.
It seems like the directory was copied from github.com/pyupio/dparse/docs with full text replacing `pyup` with `deparse`.

I suggest to replace the link with https://pyup.readthedocs.io/en/latest/readme.html#installation or just delete it and the `docs` directory alltogether.
